config/routes.rb
Rails.application.routes.draw do
 
  root :to => 'pages#home'
  get 'session/new'

  get '/f/:slug' => 'feeds#view', :as => :feed
  delete '/f/:slug' => 'feeds#destroy', :as => :delete_feed
  get '/feeds/edit/:slug' => 'feeds#edit', :as => :edit_feed
  post '/feeds/edit/:slug' => 'feeds#update', :as => :update_feed


  resources :feeds, :only => [:new, :create]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  resources :posts, :only => [:create]
  get '/posts/:id' => 'posts#view'
  delete '/posts/:id' => 'posts#destroy'

  resources :users, :only => [:new, :create]
  get '/u/:id' => 'users#view', :as => :user_home

  get 'subscriptions/new', :as => :new_subscription
  get 'subscriptions/delete'
  get 'subscriptions/create'
  get 'subscriptions/destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
    validates :slug, uniqueness: true
    belongs_to :user, :optional => true
    has_many :posts
    has_many :subscriptions


    after_create :update_slug
    before_update :assign_slug

    def create_slug
        head = self.name.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/,'')
        tail = self.id.to_s
        return head + "_" + tail
    end

    def update_slug
        update_attributes slug: assign_slug
    end

    private
        def assign_slug
            self.slug = create_slug
        end
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :feed, :optional => true

    
    
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    belongs_to :feed, :optional => true

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, :presence => true, :uniqueness => true
    has_many :feeds
    has_many :posts, :through => :feeds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user
  

    






    def url?(string)
        uri = URI.parse(string)
        %w( http https ).include?(uri.scheme)
      rescue URI::BadURIError
        false
      rescue URI::InvalidURIError
        false
    end




    private
    def fetch_user
      @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
      session[:user_id] = nil unless @current_user.present? # Log out non-existent users.
    end
  
    def check_for_login
      redirect_to login_path unless @current_user.present?
    end
  

end
  

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def new
  end

  def create
    @feed = Feed.create feed_params
    @feed.user_id = @current_user.id
    @feed.save
    # this bit was rushed minutes before submittion
    p5 = Post_factory.mint_embed_post("https://www.youtube.com/watch?v=uaaC57tcci0", @feed)
    p4 = Post_factory.mint_embed_post("https://twitter.com/Davesci/status/1315527920685703168", @feed)
    p3 = Post_factory.mint_text_post(" <h3>Faraday is a little tool to help you: </h3>   
      <h3>
          <ul>
              <li><span class='underline'>Quit a social network</span> while still keeping track of a couple key people, communities or channels</li>
              <li><span class='underline'>Hijack your habbits</span> - replace your twitter, youtube, reddit or instagram app with a feed of productive or motivational stuff</li>
              <li><span class='underline'>Spend less time on social media</span> - no algorythyms or endless feeds</li>
          </ul> 
      </h3>", @feed)
    p1 = Post_factory.mint_text_post("<h3>Welcome to your new feed 👋 </h3><br/> <h3>Paste in a link to the box above to get started, e.g. https://youtu.be/jNQXAC9IVRw .</h3>", @feed)
    
    redirect_to feed_path(@feed.slug)
  end

  def browse
     @all_feeds = Feed.all
  end

  def edit
    @feed = Feed.find_by_slug(params[:slug])
  end

  def update
    @feed = Feed.find_by_slug(params[:slug])
      if @feed.user_id == @current_user.id
        @feed.update feed_params
      end
      redirect_to user_home_path(@current_user)
  end

  def destroy
    feed = Feed.find_by_slug(params[:slug])
    feed.destroy if feed.user_id == @current_user.id
    redirect_to user_home_path(@current_user)
  end

  def view
    @feed = Feed.find_by_slug(params[:slug])
    redirect_to root_path if @feed.nil? 
    
    @posts = @feed.posts.sort_by{ |item| item.id }
    if @current_user && @current_user.id == @feed.user_id
      @editor = true
    end
  end

  private
    def feed_params
      params.require(:feed).permit(:name, :user_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
      @feeds = Feed.all
    end
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
      @user = User.new
    end
  
    def edit
    end
  
    def destroy
        post = Post.find params[:id]
        if post.feed.user_id == @current_user.id
            post.destroy
            redirect_back fallback_location: root_path  
            return
        end
        redirect_back fallback_location: root_path  
    end
  

    def create
        @feed = Feed.find(post_params[:feed_id])

        # check if post is empty
        if post_params[:content].blank? 
            redirect_back fallback_location: root_path  
            #TODO add post is blank error
            return
        end

        # check if user is logged in and allowed to post to this feed
        if !@current_user || @current_user.id != @feed.user_id 
            #TODO add permissions error
            return 
        end

        #Is the post plain text or a URL? 
        if !url?(post_params[:content]) 
             Post_factory.mint_text_post(post_params[:content], @feed) 
        else Post_factory.mint_embed_post(post_params[:content], @feed)
        end

        redirect_back fallback_location: root_path  
    end

    private
        def post_params
            params.require(:post).permit(:content, :source, :title, :feed_id)
        end
end
  

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new

  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_home_path(user.id)
    else
      # try again message here
      redirect_to login_path # GET /login
    end
  end

  def edit
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path # GET /login
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def edit
    if @current_user.present?
      @user = @current_user
      render :settings
    else redirect_to login_path
    end
  end

  def view
    begin
      @user = User.find params[:id]
    rescue 
      redirect_to root_path
    else
      render :view
    end
  end
  
  def create
    @user = User.new user_params
    if @user.save # returns true on success
      session[:user_id] = @user.id
      redirect_to "/feeds/new"
    else
      render :new
    end
  end


  private
  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    

end

app/helpers/feeds_helper.rb
module FeedsHelper

    def new_feed_posts

    end
end

app/helpers/posts_helper.rb
module PostsHelper

   

end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_header_editor.html.erb
<mesh title="heading" class="flex-center offset-icons gap2">
    <h1><%= @feed.name %></h1>
    <div class="drop drop--down">
        <a> <%= render partial: "ui_components/mbmenu" %> </a>
        <div class="drop__content -transition-slide-in">
            <div class="drop-list -size-large -position-left -border-rounded">
                <%= link_to 'Edit feed', edit_feed_path, class: "drop-list__btn" %>
                <%= link_to 'Delete feed', delete_feed_path, :method => :delete, data: { confirm: 'Are you sure you want to delete this feed?' }, class: "drop-list__btn" %>
            </div>
        </div>
    </div>
</mesh>

<%= form_for Post.new do |f| %>
    <mesh title="New post box" class="flex-center hgap2">
        <%= f.text_field :content, placeholder: "Paste a link to add to your feed" %>
        <%= f.hidden_field :feed_id, value: @feed.id %>
        <%= f.submit "+", class: "button primary submit mono", data: { disable_with: "↻" } %>
    </mesh>
<% end %>

app/views/feeds/_header_viewer.html.erb
<mesh title="heading" class="flex-center">
    <h1><%= @feed.name %></h1>
</mesh>
<mesh title="heading" class="flex-center offset-icons gap2">
    <p>viewing <%= @feed.user.name %>'s feed</p>
</mesh>

app/views/feeds/browse.html.erb
 <container> <inner>
<h3>My feeds</h3>
<% @current_user.feeds.each do |feed| %>
   <ul>
        <li>
            <%= link_to feed.name, feed_path(feed.slug)%> 
        </li>
    </ul>
<% end %>   
</inner></container> 

 <container> <inner>
<h3>All feeds</h3>
<% @all_feeds.each do |feed| %>
   <ul>
        <li>
            <%= link_to feed.name, feed_path(feed.slug)%> 
        </li>
    </ul>
<% end %>   
</container>

app/views/feeds/delete.html.erb
<h1>Feeds#delete</h1>
<p>Find me in app/views/feeds/delete.html.erb</p>

app/views/feeds/edit.html.erb
 <container> <inner>
  <h1>Edit feed</h1>

  <%= form_for @feed, url: update_feed_path, method: :post do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, value: @feed.name %>

    <%= f.submit "Save" %>

  <% end %>
</inner></container> 

app/views/feeds/new.html.erb
 <container> <inner>
<h1>Create a new feed</h1>

<%= form_for Feed.new do |f| %>
        <%= label_tag "Name your feed:"%>
        <%= f.text_field :name, placeholder: "Photography tips", :required => true %>

        <% # label_tag :feed_posts, value: "Optional - Add some content into your feed:"%>
        <% # text_area :feed_posts, placeholder: "Paste in links here. You can seperate them with a comma or a space." %>

        <%= f.submit "Create Feed", class: "button", :disable_with => '⏳' %>
  <% end %>
</inner></container> 

app/views/feeds/view.html.erb
 <container> <inner>

<% if @editor %>
    <%= render partial: "header_editor", locals: { feed: @feed } %>
<% else %>
    <%= render partial: "header_viewer", locals: { feed: @feed } %>
<%end %>

</inner></container> 


<feed>
    <mesh class="feed-inner gap4">
        <% @posts.each do |post| %>
            <%= render partial: "posts/post", locals: { post: post } %>
        <% end %>
    </mesh>
</feed>

app/views/layouts/_logo.html.erb
<a href="/" style="text-decoration: none;">
    <logo> F </logo>
</a>

app/views/layouts/_nav.html.erb
<nav aria-label="main navigation">
     <container> 
        <inner>
            <mesh class="space-between overflow">
                <%= render partial: "layouts/logo" %>

                <% if @current_user.present? %>
                    <div>
                        <%= link_to ("New feed".html_safe), new_feed_path, class: "button" %>
                        <%# link_to @current_user.name, session_edit_path, class: "button light" %> 
                        <div class="drop drop--down">
                            <a class="button bold"><%= "#{@current_user.name} &nbsp;▾".html_safe %> </a>
                            <div class="drop__content -transition-slide-in">
                                <div class="drop-list -size-large -position-left  ">
                                    <small><%= @current_user.email %> </small>
                                    <%= link_to "My feeds", "/u/#{@current_user.id}", class: "drop-list__btn" %>
                                    <%= link_to "Logout", login_path, :method => 'delete', class: "drop-list__btn red" %>
                                </div>
                            </div>
                        </div>
                    </div>
                <% else %>
                    <div>
                        <%= link_to "Log in", login_path, class: "button" %>
                        <%= link_to 'Sign up', new_user_path, class: "button primary" %>
                    </div>
                <% end %>
            </mesh>
        </inner>
    </container> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaradayApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@400;600&display=swap" rel="stylesheet">        
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'type', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/nav" %>
    <main>
      <%= yield %>
    </main>

  </body>

</html>

app/views/pages/home.html.erb
  <container class="yellow-background no-padding" title="faraday header"> 
    <inner class="max-width-wider">
        <mesh class="flex-stretch">
            <section class="marketing-section gap7">
                <div class="gap3">
                    <h4>FARADAY TUBE</h4>
                    <h1>Youtube, Twitter and IG without 
                        <span style="text-decoration: line-through;">algorithms</span>, 
                        <span style="text-decoration: line-through;">rabbit holes</span> or 
                        <span style="text-decoration: line-through;">comments</span>
                    </h1>
                </div>
                <% if @current_user.present? %>
                    <%= link_to "View my feeds", user_home_path(@current_user), class: "button primary medium" %>
                <% else %>   
                    <%= link_to "Try it out", new_user_path, class: "button primary medium" %>
                <% end %>   
            </section>

            <div class="desktop-header-image"></div>

        </mesh>
        <div class="mobile-header-image blue-background"></div>
    </inner>
</container> 
<container class="no-padding" > 
    <inner class="max-width-wider">
        <section class="marketing-section gap4">
            <h1>Browse feeds:</h1>
        
            <% @feeds.each do |feed| %>
                <%= render partial: "ui_components/feed_card", locals: { feed: feed } %>
            <% end %>

            <% if @current_user.present? %>
                <%= link_to ("Create a new feed".html_safe), new_feed_path, class: "button primary" %>
            <% end %>
        </section>
    </inner>
</container> 
 

app/views/posts/_post.html.erb
<post title="<%= post.title %>" type="<%= post.post_type %>" provider="<%= post.provider_name %>" >
    <content>
        <%= raw(post.content) %>
    </content>
    <handle>
        <mesh>
            <dot>
                <%= render partial: "ui_components/read_state_dot", locals: { post: post } %>
            </dot>
            <posttitle>
                <small>
                    <%= raw(post.title) %>
                </small>
            </posttitle>
            <iconcontainer>
                <% if @current_user.present? && post.feed.user_id == @current_user.id %>
                    <div class="drop drop--up">
                        <a> <%= render partial: "ui_components/mbmenu" %> </a>
                        <div class="drop__content -transition-slide-in">
                            <div class="drop-list -size-large -position-left -border-rounded">
                                <%= link_to 'Remove post', "/posts/#{post.id}", :method => :delete, class: "drop-list__btn" %>
                            </div>
                        </div>
                    </div>
                <% end %>
            </iconcontainer>
        </mesh>
    </handle>
</post>

app/views/posts/can be deleted.html.erb
 <container> <inner>
<h3>My posts</h3>
<% @current_user.feeds.each do |feed| %>
   <ul>
        <li>
            <%= link_to feed.name, feed_path(feed.slug)%> 
        </li>
    </ul>
<% end %>   
</inner></container> 

 <container> <inner>
<h3>All feeds</h3>
<% @all_feeds.each do |feed| %>
   <ul>
        <li>
            <%= link_to feed.name, feed_path(feed.slug)%> 
        </li>
    </ul>
<% end %>   
</container>

app/views/posts/rename.html.erb
<container>
<h3>My posts</h3>
<% @current_user.feeds.each do |feed| %>
   <ul>
        <li>
            <%= link_to feed.name, feed_path(feed.slug)%> 
        </li>
    </ul>
<% end %>   
</container>

<container>
<h3>All feeds</h3>
<% @all_feeds.each do |feed| %>
   <ul>
        <li>
            <%= link_to feed.name, feed_path(feed.slug)%> 
        </li>
    </ul>
<% end %>   
</container>

app/views/session/edit.html.erb
 <container> <inner>
    <h1>Edit your profile</h1>

    <% if @current_user.present? %>

        <% if @current_user.errors.any? %>
        <ol>
            <% @current_user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ol>
        <% end %>

        <%= form_for @current_user  do |f| %>
            <%= f.label :email %>
            <%= f.email_field :email, :required => true %>

            <%= f.submit "Save" %>
        <% end %>

    <% end %>
</inner></container> 

app/views/session/new.html.erb
 <container> <inner>
  <h1>Log In</h1>

  <%= form_tag login_path do %>

      <%= label_tag :email %>
      <%= email_field_tag :email %>

      <%= label_tag :password %>
      <%= password_field_tag :password %>

    <%= submit_tag "Sign In"%>
  <% end %>
</inner></container> 

app/views/ui_components/_feed_card.html.erb
<% user = User.find feed.user_id %>

<card title="<%= feed.name %>"> 
    <%= link_to "#{feed.name}", feed_path(feed.slug)%> 
    <small> by <%= user.name %> </small>
</card>

app/views/ui_components/_mbmenu.html.erb
<icon>
    <svg width="18" height="4" viewBox="0 0 18 4" fill="none" xmlns="http://www.w3.org/2000/svg">
        <circle cx="16" cy="2" r="2" fill="#A69DAD"/>
        <circle cx="9" cy="2" r="2" fill="#A69DAD"/>
        <circle cx="2" cy="2" r="2" fill="#A69DAD"/>
    </svg>
 </icon>

app/views/ui_components/_read_state_dot.html.erb
<% if post == "read" %>
        <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
            <circle cx="6" cy="6" r="6" fill="#FFD66C"/>
        </svg>
    <% else %>
        <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
            <circle cx="6" cy="6" r="5.5" stroke="#A69DAD"/>
        </svg>
<% end %>

app/views/users/new.html.erb
 <container> <inner>
  <h1>Sign Up</h1>

  <% if @user.errors.any? %>
    <ol>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ol>
  <% end %>

  <%= form_for @user do |f| %>

      <%= f.label :email %>
      <%= f.email_field :email, :required => true %>

      <%= label_tag "Your name" %>
      <%= f.text_field :name %>

      <%= f.label :password %>
      <%= f.password_field :password, :required => true %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, :required => true %>

    <%= f.submit "Sign up" %>
  <% end %>
</inner></container> 

app/views/users/view.html.erb
<container> 
    <inner>
        <h1>
            <%= @user.name %>'s feeds:
        </h1>

         <% if @user.feeds.any? %>
            <% @user.feeds.each do |feed| %>
                <%= render partial: "ui_components/feed_card", locals: { feed: feed } %>
            <% end %>   
        <% else %>
            <card>
                <h3> Looks like there are no feeds here yet.... </h3>
            </card>
        <% end %>

        <% if @current_user.present? && @user.id == @current_user.id %>
            <%= link_to ("Create a new feed".html_safe), new_feed_path, class: "button primary" %>
        <% end %>

    </inner>
</container> 